# Generated by Django 5.1.1 on 2024-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.EmailField(max_length=254)),
                ("grave", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("other_Name", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(max_length=15)),
                ("is_alive", models.BooleanField()),
                ("content", models.TextField()),
                ("dob", models.DateTimeField()),
                ("dod", models.DateTimeField(blank=True, null=True)),
                ("voice_id", models.CharField(blank=True, max_length=255, null=True)),
                ("owner", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="GraveImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grave", models.IntegerField()),
                ("image", models.URLField(max_length=255)),
                ("owner", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="GraveVisitors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grave", models.IntegerField()),
                ("visitor", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("gift", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.IntegerField()),
                ("user_msg", models.TextField()),
                ("ai_msg", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
