# Generated by Django 5.1.1 on 2024-09-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="ai_msg",
            field=models.TextField(blank=True, null=True),
        ),
    ]
