# Generated by Django 5.1.1 on 2024-09-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_graveimages_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="voice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
