# Generated by Django 5.1.1 on 2024-09-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_messages_voice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="voice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
