# Generated by Django 5.1.1 on 2024-09-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_messages_voice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="grave",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
